title: JDY's learning intelligence
description:  Intelligence Curriculum Guide
url: https://tool2000.github.io/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
