title: JDY's learning intelligence
description:  Intelligence Curriculum Guide
url: https://tool2000.github.io/
baseurl: ''
theme_skin: blue
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: ""
incremental: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
